# Generated by Django 2.2.13 on 2020-10-22 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('p_libruary', '0004_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(blank=True, max_length=2),
        ),
    ]
