# Generated by Django 2.2.13 on 2020-10-22 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('p_libruary', '0005_userprofile_country'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='country',
        ),
    ]
