# Generated by Django 2.2.6 on 2020-07-28 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('p_libruary', '0008_auto_20200723_0728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='p_libruary.Publisher'),
        ),
        migrations.AlterField(
            model_name='publisher',
            name='name',
            field=models.TextField(max_length=128),
        ),
    ]
